[env:smartload_esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions/partitions_4MB.csv

build_flags =
    -DLOG_LOCAL_LEVEL=ESP_LOG_INFO
    -DDEFAULT_WIFI_SSID=\"\"
    -DDEFAULT_WIFI_PASS=\"\"
    -DCONFIG_MQTT_PROTOCOL_311
    -DCONFIG_MQTT_TRANSPORT_SSL

monitor_filters =
    esp32_exception_decoder