[common]
platform = espressif32
framework = espidf
monitor_speed = 115200
build_flags =
    -DLOG_LOCAL_LEVEL=ESP_LOG_INFO
    -DCONFIG_MQTT_PROTOCOL_311
    -DCONFIG_MQTT_TRANSPORT_SSL

[esp32dev_common]
board = esp32dev
board_build.partitions = partitions/partitions_4MB.csv

[esp32s3_common]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3

[env:smartload_esp32dev]
extends =
    common
    esp32dev_common
build_flags =
    ${common.build_flags}
    -DHARDWARE_ESP32DEV
    -DDEFAULT_WIFI_SSID=\"\"
    -DDEFAULT_WIFI_PASS=\"\"
monitor_filters =
    esp32_exception_decoder

[env:smartload_relcon]
extends = common
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = partitions/partitions_4MB.csv
board_build.sdkconfig_defaults =
    sdkconfig.defaults.smartload_relcon
build_flags =
    ${common.build_flags}
    -DCONFIG_MQTT_PROTOCOL_311
    -DCONFIG_MQTT_TRANSPORT_SSL
    -DHARDWARE_RELCON
upload_speed= 115200

[env:orpack]
extends = common
board = esp32s3_16MB
board_build.mcu = esp32s3
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions/partitions_16MB.csv
board_build.sdkconfig_defaults =
    sdkconfig.defaults.orpack
build_flags =
    ${common.build_flags}
    -DCONFIG_MQTT_PROTOCOL_311
    -DCONFIG_MQTT_TRANSPORT_SSL
    -DHARDWARE_ORPACK
    -I src
upload_speed = 921600

[env:smartload_eviden]
extends =
    common
    esp32s3_common
board_build.flash_size = 8MB
board_build.partitions = partitions/partitions_8MB.csv
build_flags =
    ${common.build_flags}
    -DHARDWARE_EVIDEN

[env:smartload_new_pcb]
extends =
    common
    esp32s3_common
board_build.flash_size = 8MB
board_build.partitions = partitions/partitions_8MB.csv
board_build.sdkconfig = sdkconfig.smartload_new_pcb
build_flags =
    ${common.build_flags}
    -DHARDWARE_NEW_PCB
    -DDEBUG_MODE
    -DDEFAULT_WIFI_SSID=\"ConnectSecure\"
    -DDEFAULT_WIFI_PASS=\"Con@Vjn#560040\"
monitor_filters =
    esp32_exception_decoder